export const dataScreen1 = [
  {
    "Business Unit": "Commercial",
    "Division": "Car Powertrain Technology",
    "Subdivision": "Automatic Transmissions",
    "Department": "Body design 1",
    "Manager": "Markus Schwabe",
    "% Design Errors": 90,
    "% Schedule delays": 34,
    "% Cost overrun": 11,
    "Iterations per design": 7.8,
    "% Rushed design": 31,
    "Design digitization": 81,
    "SME involvement": 34,
    "Predicted Design Errors": 7
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Powertrain Technology",
    "Subdivision": "Dual Clutch & Manual Transmissions",
    "Department": "Body design 2",
    "Manager": "Markus Schmidt",
    "% Design Errors": 53,
    "% Schedule delays": 65,
    "% Cost overrun": 65,
    "Iterations per design": 0.7,
    "% Rushed design": 24,
    "Design digitization": 41,
    "SME involvement": 23,
    "Predicted Design Errors": 8
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Powertrain Technology",
    "Subdivision": "Powertrain Modules",
    "Department": "Body design 3",
    "Manager": "Claus Umnus",
    "% Design Errors": 40,
    "% Schedule delays": 21,
    "% Cost overrun": 18,
    "Iterations per design": 4.9,
    "% Rushed design": 34,
    "Design digitization": 97,
    "SME involvement": 30,
    "Predicted Design Errors": 14
  },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Car Powertrain Technology",
  //   "Subdivision": "Valve",
  //   "Department": "Body design functional",
  //   "Manager": "David",
  //   "% Design Errors": 61,
  //   "% Schedule delays": 71,
  //   "% Cost overrun": 14,
  //   "Iterations per design": 1,
  //   "% Rushed design": 8,
  //   "Design digitization": 70,
  //   "SME involvement": 75,
  //   "Predicted Design Errors": 1
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Car Powertrain Technology",
  //   "Subdivision": "Transmission",
  //   "Department": "Body designseats",
  //   "Manager": "Eileen",
  //   "% Design Errors": 36,
  //   "% Schedule delays": 72,
  //   "% Cost overrun": 91,
  //   "Iterations per design": 5.1,
  //   "% Rushed design": 3,
  //   "Design digitization": 1,
  //   "SME involvement": 32,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Car Powertrain Technology",
  //   "Subdivision": "Differential",
  //   "Department": "Engineering and data innovation",
  //   "Manager": "Frank",
  //   "% Design Errors": 6,
  //   "% Schedule delays": 61,
  //   "% Cost overrun": 34,
  //   "Iterations per design": 1.3,
  //   "% Rushed design": 81,
  //   "Design digitization": 93,
  //   "SME involvement": 27,
  //   "Predicted Design Errors": 1
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Car Powertrain Technology",
  //   "Subdivision": "Braking",
  //   "Department": "Engineering design chassis",
  //   "Manager": "Ginevra",
  //   "% Design Errors": 7,
  //   "% Schedule delays": 44,
  //   "% Cost overrun": 42,
  //   "Iterations per design": 0.6,
  //   "% Rushed design": 8,
  //   "Design digitization": 29,
  //   "SME involvement": 42,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Car Powertrain Technology",
  //   "Subdivision": "Software",
  //   "Department": "Electronic systems 1",
  //   "Manager": "Harold",
  //   "% Design Errors": 50,
  //   "% Schedule delays": 20,
  //   "% Cost overrun": 52,
  //   "Iterations per design": 4.7,
  //   "% Rushed design": 3,
  //   "Design digitization": 81,
  //   "SME involvement": 73,
  //   "Predicted Design Errors": 1
  // },
  {
    "Business Unit": "Commercial",
    "Division": "Car Chassis Technology",
    "Subdivision": "Chassis Systems & Modules",
    "Department": "Electronic system 2",
    "Manager": "Matthias Raulf",
    "% Design Errors": 62,
    "% Schedule delays": 70,
    "% Cost overrun": 12,
    "Iterations per design": 4.5,
    "% Rushed design": 12,
    "Design digitization": 68,
    "SME involvement": 33,
    "Predicted Design Errors": 15
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Chassis Technology",
    "Subdivision": "Chassis Components",
    "Department": "Interior design 1",
    "Manager": "Steffen Reichelt",
    "% Design Errors": 82,
    "% Schedule delays": 65,
    "% Cost overrun": 10,
    "Iterations per design": 8.7,
    "% Rushed design": 62,
    "Design digitization": 75,
    "SME involvement": 32,
    "Predicted Design Errors": 12
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Chassis Technology",
    "Subdivision": "Suspension Technology",
    "Department": "Integrated Vehicle systems",
    "Manager": "Mario Sabel",
    "% Design Errors": 9,
    "% Schedule delays": 20,
    "% Cost overrun": 55,
    "Iterations per design": 8.9,
    "% Rushed design": 63,
    "Design digitization": 19,
    "SME involvement": 38,
    "Predicted Design Errors": 30
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Chassis Technology",
    "Subdivision": "Chassis Actuators",
    "Department": "Quality engineering",
    "Manager": "Ingo Hermansa",
    "% Design Errors": 43,
    "% Schedule delays": 10,
    "% Cost overrun": 43,
    "Iterations per design": 6.2,
    "% Rushed design": 60,
    "Design digitization": 54,
    "SME involvement": 62,
    "Predicted Design Errors": 2
  },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Car Chassis Technology",
  //   "Subdivision": "Transmission",
  //   "Department": "Production engineering",
  //   "Manager": "Bart",
  //   "% Design Errors": 36,
  //   "% Schedule delays": 39,
  //   "% Cost overrun": 70,
  //   "Iterations per design": 7.3,
  //   "% Rushed design": 57,
  //   "Design digitization": 40,
  //   "SME involvement": 48,
  //   "Predicted Design Errors": 1
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Car Chassis Technology",
  //   "Subdivision": "Differential",
  //   "Department": "Vehicle Performance Dvelopment",
  //   "Manager": "Candice",
  //   "% Design Errors": 39,
  //   "% Schedule delays": 45,
  //   "% Cost overrun": 77,
  //   "Iterations per design": 7.9,
  //   "% Rushed design": 93,
  //   "Design digitization": 72,
  //   "SME involvement": 36,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Car Chassis Technology",
  //   "Subdivision": "Braking",
  //   "Department": "Vehicle planning production engineering",
  //   "Manager": "David",
  //   "% Design Errors": 36,
  //   "% Schedule delays": 71,
  //   "% Cost overrun": 28,
  //   "Iterations per design": 7.3,
  //   "% Rushed design": 95,
  //   "Design digitization": 57,
  //   "SME involvement": 6,
  //   "Predicted Design Errors": 1
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Car Chassis Technology",
  //   "Subdivision": "Software",
  //   "Department": "Body design 1",
  //   "Manager": "Eileen",
  //   "% Design Errors": 62,
  //   "% Schedule delays": 72,
  //   "% Cost overrun": 30,
  //   "Iterations per design": 7.6,
  //   "% Rushed design": 42,
  //   "Design digitization": 39,
  //   "SME involvement": 9,
  //   "Predicted Design Errors": 3
  // },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "Truck & Van Driveline Technology",
    "Department": "Body design 2",
    "Manager": "Winfried Gründler",
    "% Design Errors": 46,
    "% Schedule delays": 16,
    "% Cost overrun": 63,
    "Iterations per design": 5.4,
    "% Rushed design": 58,
    "Design digitization": 51,
    "SME involvement": 66,
    "Predicted Design Errors": 19
  },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "Axle & Transmission System for Buses & Coaches",
    "Department": "Body design 3",
    "Manager": "Dr. Andreas Grossl",
    "% Design Errors": 7,
    "% Schedule delays": 37,
    "% Cost overrun": 30,
    "Iterations per design": 9.8,
    "% Rushed design": 24,
    "Design digitization": 55,
    "SME involvement": 34,
    "Predicted Design Errors": 30
  },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "CV Chassis Technology",
    "Department": "Body design functional",
    "Manager": "Joachim Holzner",
    "% Design Errors": 40,
    "% Schedule delays": 72,
    "% Cost overrun": 42,
    "Iterations per design": 4.7,
    "% Rushed design": 15,
    "Design digitization": 67,
    "SME involvement": 95,
    "Predicted Design Errors": 8
  },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "CV Powertrain Modules",
    "Department": "Body designseats",
    "Manager": "Kleber Barros Vinhas",
    "% Design Errors": 34,
    "% Schedule delays": 78,
    "% Cost overrun": 18,
    "Iterations per design": 7,
    "% Rushed design": 68,
    "Design digitization": 7,
    "SME involvement": 28,
    "Predicted Design Errors": 5
  },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "CV Steering Systems",
    "Department": "Engineering and data innovation",
    "Manager": "Tomas Bozek",
    "% Design Errors": 81,
    "% Schedule delays": 25,
    "% Cost overrun": 8,
    "Iterations per design": 9.8,
    "% Rushed design": 42,
    "Design digitization": 58,
    "SME involvement": 54,
    "Predicted Design Errors": 6
  },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Commercial Vehicle Technology",
  //   "Subdivision": "Differential",
  //   "Department": "Engineering design chassis",
  //   "Manager": "Krishna",
  //   "% Design Errors": 2,
  //   "% Schedule delays": 63,
  //   "% Cost overrun": 15,
  //   "Iterations per design": 8.6,
  //   "% Rushed design": 66,
  //   "Design digitization": 15,
  //   "SME involvement": 91,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Commercial Vehicle Technology",
  //   "Subdivision": "Braking",
  //   "Department": "Electronic systems 1",
  //   "Manager": "Anastasia",
  //   "% Design Errors": 61,
  //   "% Schedule delays": 90,
  //   "% Cost overrun": 86,
  //   "Iterations per design": 0.1,
  //   "% Rushed design": 61,
  //   "Design digitization": 78,
  //   "SME involvement": 2,
  //   "Predicted Design Errors": 3
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Commercial Vehicle Technology",
  //   "Subdivision": "Software",
  //   "Department": "Electronic system 2",
  //   "Manager": "Bart",
  //   "% Design Errors": 78,
  //   "% Schedule delays": 88,
  //   "% Cost overrun": 70,
  //   "Iterations per design": 6.6,
  //   "% Rushed design": 74,
  //   "Design digitization": 66,
  //   "SME involvement": 61,
  //   "Predicted Design Errors": 2
  // },
  {
    "Business Unit": "Commercial",
    "Division": "Industrial Technology",
    "Subdivision": "Off-Highway & Test Systems",
    "Department": "Interior design 1",
    "Manager": "Udo Kneitz",
    "% Design Errors": 3,
    "% Schedule delays": 58,
    "% Cost overrun": 33,
    "Iterations per design": 1.2,
    "% Rushed design": 30,
    "Design digitization": 34,
    "SME involvement": 16,
    "Predicted Design Errors": 5
  },
  {
    "Business Unit": "Commercial",
    "Division": "Industrial Technology",
    "Subdivision": "Aviation Technology",
    "Department": "Integrated Vehicle systems",
    "Manager": "David",
    "% Design Errors": 85,
    "% Schedule delays": 46,
    "% Cost overrun": 33,
    "Iterations per design": 4.7,
    "% Rushed design": 17,
    "Design digitization": 36,
    "SME involvement": 52,
    "Predicted Design Errors": 9
  },
  {
    "Business Unit": "Commercial",
    "Division": "Industrial Technology",
    "Subdivision": "Marine & Special Driveline Technology",
    "Department": "Quality engineering",
    "Manager": "Daniel Härter",
    "% Design Errors": 16,
    "% Schedule delays": 35,
    "% Cost overrun": 82,
    "Iterations per design": 3.7,
    "% Rushed design": 51,
    "Design digitization": 54,
    "SME involvement": 43,
    "Predicted Design Errors": 20
  },
  {
    "Business Unit": "Commercial",
    "Division": "Industrial Technology",
    "Subdivision": "Wind Power Technology & Industrial Drives",
    "Department": "Production engineering",
    "Manager": "Udo Kneitz",
    "% Design Errors": 19,
    "% Schedule delays": 32,
    "% Cost overrun": 60,
    "Iterations per design": 5.9,
    "% Rushed design": 10,
    "Design digitization": 59,
    "SME involvement": 46,
    "Predicted Design Errors": 30
  },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Industrial Technology",
  //   "Subdivision": "Aviation Technology",
  //   "Department": "Vehicle Performance Development",
  //   "Manager": "Burkhard Siebert",
  //   "% Design Errors": 33,
  //   "% Schedule delays": 62,
  //   "% Cost overrun": 24,
  //   "Iterations per design": 9,
  //   "% Rushed design": 62,
  //   "Design digitization": 57,
  //   "SME involvement": 64,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Industrial Technology",
  //   "Subdivision": "Wind Power Technology",
  //   "Department": "Vehicle planning production engineering",
  //   "Manager": "Mitja Schulz",
  //   "% Design Errors": 40,
  //   "% Schedule delays": 13,
  //   "% Cost overrun": 46,
  //   "Iterations per design": 8.2,
  //   "% Rushed design": 64,
  //   "Design digitization": 98,
  //   "SME involvement": 64,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Industrial Technology",
  //   "Subdivision": "Braking",
  //   "Department": "Body design 1",
  //   "Manager": "Isabel",
  //   "% Design Errors": 31,
  //   "% Schedule delays": 7,
  //   "% Cost overrun": 42,
  //   "Iterations per design": 5.4,
  //   "% Rushed design": 2,
  //   "Design digitization": 31,
  //   "SME involvement": 97,
  //   "Predicted Design Errors": 3
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "Industrial Technology",
  //   "Subdivision": "Software",
  //   "Department": "Body design 2",
  //   "Manager": "Jose",
  //   "% Design Errors": 73,
  //   "% Schedule delays": 4,
  //   "% Cost overrun": 18,
  //   "Iterations per design": 0.9,
  //   "% Rushed design": 29,
  //   "Design digitization": 53,
  //   "SME involvement": 94,
  //   "Predicted Design Errors": 3
  // },
  {
    "Business Unit": "Commercial",
    "Division": "E-Mobility",
    "Subdivision": "Electronic Systems",
    "Department": "Body design 3",
    "Manager": "Harald Deiss",
    "% Design Errors": 2,
    "% Schedule delays": 55,
    "% Cost overrun": 85,
    "Iterations per design": 7.3,
    "% Rushed design": 92,
    "Design digitization": 33,
    "SME involvement": 74,
    "Predicted Design Errors": 16
  },
  {
    "Business Unit": "Commercial",
    "Division": "E-Mobility",
    "Subdivision": "Electric Traction Drive",
    "Department": "Body design functional",
    "Manager": "Dr. Andreas Fink",
    "% Design Errors": 58,
    "% Schedule delays": 94,
    "% Cost overrun": 73,
    "Iterations per design": 7.4,
    "% Rushed design": 30,
    "Design digitization": 8,
    "SME involvement": 91,
    "Predicted Design Errors": 18
  },
  {
    "Business Unit": "Commercial",
    "Division": "E-Mobility",
    "Subdivision": "Axle Drives",
    "Department": "Body designseats",
    "Manager": "Kay Schmidt",
    "% Design Errors": 37,
    "% Schedule delays": 25,
    "% Cost overrun": 93,
    "Iterations per design": 4,
    "% Rushed design": 35,
    "Design digitization": 66,
    "SME involvement": 29,
    "Predicted Design Errors": 20
  },
  {
    "Business Unit": "Commercial",
    "Division": "E-Mobility",
    "Subdivision": "Electronic Interfaces",
    "Department": "Engineering and data innovation",
    "Manager": "Thomas Buda",
    "% Design Errors": 27,
    "% Schedule delays": 92,
    "% Cost overrun": 73,
    "Iterations per design": 2.8,
    "% Rushed design": 52,
    "Design digitization": 34,
    "SME involvement": 64,
    "Predicted Design Errors": 9
  },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "E-Mobility",
  //   "Subdivision": "Electronic Systems",
  //   "Department": "Engineering design chassis",
  //   "Manager": "David",
  //   "% Design Errors": 57,
  //   "% Schedule delays": 32,
  //   "% Cost overrun": 87,
  //   "Iterations per design": 8.5,
  //   "% Rushed design": 7,
  //   "Design digitization": 84,
  //   "SME involvement": 36,
  //   "Predicted Design Errors": 3
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "E-Mobility",
  //   "Subdivision": "Differential",
  //   "Department": "Electronic systems 1",
  //   "Manager": "Eileen",
  //   "% Design Errors": 30,
  //   "% Schedule delays": 29,
  //   "% Cost overrun": 12,
  //   "Iterations per design": 5.8,
  //   "% Rushed design": 99,
  //   "Design digitization": 46,
  //   "SME involvement": 8,
  //   "Predicted Design Errors": 3
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "E-Mobility",
  //   "Subdivision": "Braking",
  //   "Department": "Electronic system 2",
  //   "Manager": "Frank",
  //   "% Design Errors": 62,
  //   "% Schedule delays": 3,
  //   "% Cost overrun": 16,
  //   "Iterations per design": 4.5,
  //   "% Rushed design": 54,
  //   "Design digitization": 66,
  //   "SME involvement": 32,
  //   "Predicted Design Errors": 3
  // },
  // {
  //   "Business Unit": "Commercial",
  //   "Division": "E-Mobility",
  //   "Subdivision": "Software",
  //   "Department": "Interior design 1",
  //   "Manager": "Ginevra",
  //   "% Design Errors": 6,
  //   "% Schedule delays": 68,
  //   "% Cost overrun": 5,
  //   "Iterations per design": 7.9,
  //   "% Rushed design": 19,
  //   "Design digitization": 84,
  //   "SME involvement": 83,
  //   "Predicted Design Errors": 2
  // },
  {
    "Business Unit": "Government",
    "Division": "Aftermarket",
    "Subdivision": "Independent Aftermarket",
    "Department": "Integrated Vehicle systems",
    "Manager": "Harold",
    "% Design Errors": 50,
    "% Schedule delays": 95,
    "% Cost overrun": 4,
    "Iterations per design": 8.1,
    "% Rushed design": 19,
    "Design digitization": 44,
    "SME involvement": 83,
    "Predicted Design Errors": 5
  },
  {
    "Business Unit": "Government",
    "Division": "Aftermarket",
    "Subdivision": "Original Equipment Supplier/Specific Original Equipment",
    "Department": "Quality engineering",
    "Manager": "Isabel",
    "% Design Errors": 1,
    "% Schedule delays": 26,
    "% Cost overrun": 6,
    "Iterations per design": 2.4,
    "% Rushed design": 14,
    "Design digitization": 60,
    "SME involvement": 33,
    "Predicted Design Errors": 12
  },
  {
    "Business Unit": "Government",
    "Division": "Aftermarket",
    "Subdivision": "Manufacturing",
    "Department": "Production engineering",
    "Manager": "Jose",
    "% Design Errors": 45,
    "% Schedule delays": 19,
    "% Cost overrun": 71,
    "Iterations per design": 0.2,
    "% Rushed design": 9,
    "Design digitization": 91,
    "SME involvement": 88,
    "Predicted Design Errors": 6
  },
  {
    "Business Unit": "Government",
    "Division": "Aftermarket",
    "Subdivision": "Friction Materials Group",
    "Department": "Vehicle Performance Dvelopment",
    "Manager": "Krishna",
    "% Design Errors": 95,
    "% Schedule delays": 90,
    "% Cost overrun": 80,
    "Iterations per design": 3,
    "% Rushed design": 17,
    "Design digitization": 57,
    "SME involvement": 39,
    "Predicted Design Errors": 11
  },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Aftermarket",
  //   "Subdivision": "Transmission",
  //   "Department": "Vehicle planning production engineering",
  //   "Manager": "Anastasia",
  //   "% Design Errors": 100,
  //   "% Schedule delays": 0,
  //   "% Cost overrun": 98,
  //   "Iterations per design": 5.6,
  //   "% Rushed design": 66,
  //   "Design digitization": 63,
  //   "SME involvement": 82,
  //   "Predicted Design Errors": 1
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Aftermarket",
  //   "Subdivision": "Differential",
  //   "Department": "Body design 1",
  //   "Manager": "Bart",
  //   "% Design Errors": 46,
  //   "% Schedule delays": 56,
  //   "% Cost overrun": 86,
  //   "Iterations per design": 6.6,
  //   "% Rushed design": 70,
  //   "Design digitization": 22,
  //   "SME involvement": 17,
  //   "Predicted Design Errors": 3
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Aftermarket",
  //   "Subdivision": "Braking",
  //   "Department": "Body design 2",
  //   "Manager": "Candice",
  //   "% Design Errors": 64,
  //   "% Schedule delays": 71,
  //   "% Cost overrun": 5,
  //   "Iterations per design": 9.5,
  //   "% Rushed design": 30,
  //   "Design digitization": 45,
  //   "SME involvement": 73,
  //   "Predicted Design Errors": 3
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Aftermarket",
  //   "Subdivision": "Software",
  //   "Department": "Body design 3",
  //   "Manager": "David",
  //   "% Design Errors": 60,
  //   "% Schedule delays": 17,
  //   "% Cost overrun": 70,
  //   "Iterations per design": 4.9,
  //   "% Rushed design": 49,
  //   "Design digitization": 26,
  //   "SME involvement": 71,
  //   "Predicted Design Errors": 1
  // },
  {
    "Business Unit": "Government",
    "Division": "Electronics & ADAS",
    "Subdivision": "Advanced Driver Assistance Systems",
    "Department": "Body design functional",
    "Manager": "Aine Denari",
    "% Design Errors": 28,
    "% Schedule delays": 30,
    "% Cost overrun": 64,
    "Iterations per design": 1.8,
    "% Rushed design": 24,
    "Design digitization": 76,
    "SME involvement": 93,
    "Predicted Design Errors": 8
  },
  {
    "Business Unit": "Government",
    "Division": "Electronics & ADAS",
    "Subdivision": "Passive Safety Electronics",
    "Department": "Body designseats",
    "Manager": "Jared Jacobs",
    "% Design Errors": 11,
    "% Schedule delays": 42,
    "% Cost overrun": 37,
    "Iterations per design": 0.6,
    "% Rushed design": 47,
    "Design digitization": 41,
    "SME involvement": 47,
    "Predicted Design Errors": 2
  },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Electronics & ADAS",
  //   "Subdivision": "Fuel",
  //   "Department": "Engineering and data innovation",
  //   "Manager": "Ginevra",
  //   "% Design Errors": 25,
  //   "% Schedule delays": 96,
  //   "% Cost overrun": 43,
  //   "Iterations per design": 3.9,
  //   "% Rushed design": 68,
  //   "Design digitization": 70,
  //   "SME involvement": 14,
  //   "Predicted Design Errors": 1
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Electronics & ADAS",
  //   "Subdivision": "Valve",
  //   "Department": "Engineering design chassis",
  //   "Manager": "Harold",
  //   "% Design Errors": 88,
  //   "% Schedule delays": 95,
  //   "% Cost overrun": 88,
  //   "Iterations per design": 7.8,
  //   "% Rushed design": 67,
  //   "Design digitization": 40,
  //   "SME involvement": 95,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Electronics & ADAS",
  //   "Subdivision": "Transmission",
  //   "Department": "Electronic systems 1",
  //   "Manager": "Isabel",
  //   "% Design Errors": 67,
  //   "% Schedule delays": 6,
  //   "% Cost overrun": 97,
  //   "Iterations per design": 8.3,
  //   "% Rushed design": 9,
  //   "Design digitization": 1,
  //   "SME involvement": 78,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Electronics & ADAS",
  //   "Subdivision": "Differential",
  //   "Department": "Electronic system 2",
  //   "Manager": "Jose",
  //   "% Design Errors": 70,
  //   "% Schedule delays": 55,
  //   "% Cost overrun": 91,
  //   "Iterations per design": 2,
  //   "% Rushed design": 91,
  //   "Design digitization": 30,
  //   "SME involvement": 5,
  //   "Predicted Design Errors": 1
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Electronics & ADAS",
  //   "Subdivision": "Braking",
  //   "Department": "Interior design 1",
  //   "Manager": "Krishna",
  //   "% Design Errors": 75,
  //   "% Schedule delays": 83,
  //   "% Cost overrun": 64,
  //   "Iterations per design": 0.4,
  //   "% Rushed design": 73,
  //   "Design digitization": 35,
  //   "SME involvement": 75,
  //   "Predicted Design Errors": 3
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Electronics & ADAS",
  //   "Subdivision": "Software",
  //   "Department": "Integrated Vehicle systems",
  //   "Manager": "Anastasia",
  //   "% Design Errors": 38,
  //   "% Schedule delays": 75,
  //   "% Cost overrun": 65,
  //   "Iterations per design": 7.4,
  //   "% Rushed design": 43,
  //   "Design digitization": 33,
  //   "SME involvement": 61,
  //   "Predicted Design Errors": 3
  // },
  {
    "Business Unit": "Government",
    "Division": "Passive Safety Systems",
    "Subdivision": "Inflatable Restraint Systems",
    "Department": "Quality engineering",
    "Manager": "Joe Gaus",
    "% Design Errors": 99,
    "% Schedule delays": 61,
    "% Cost overrun": 65,
    "Iterations per design": 3.3,
    "% Rushed design": 76,
    "Design digitization": 19,
    "SME involvement": 83,
    "Predicted Design Errors": 9
  },
  {
    "Business Unit": "Government",
    "Division": "Passive Safety Systems",
    "Subdivision": "Seat Belt Systems",
    "Department": "Production engineering",
    "Manager": "Dr. Petra Mayer",
    "% Design Errors": 28,
    "% Schedule delays": 69,
    "% Cost overrun": 53,
    "Iterations per design": 1.3,
    "% Rushed design": 53,
    "Design digitization": 64,
    "SME involvement": 28,
    "Predicted Design Errors": 19
  },
  {
    "Business Unit": "Government",
    "Division": "Passive Safety Systems",
    "Subdivision": "Steering Wheel Systems",
    "Department": "Vehicle Performance Dvelopment",
    "Manager": "Alexander Heilig",
    "% Design Errors": 43,
    "% Schedule delays": 96,
    "% Cost overrun": 46,
    "Iterations per design": 7.4,
    "% Rushed design": 69,
    "Design digitization": 57,
    "SME involvement": 67,
    "Predicted Design Errors": 14
  },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Passive Safety Systems",
  //   "Subdivision": "Inflators",
  //   "Department": "Vehicle planning production engineering",
  //   "Manager": "Eileen",
  //   "% Design Errors": 42,
  //   "% Schedule delays": 82,
  //   "% Cost overrun": 39,
  //   "Iterations per design": 7.5,
  //   "% Rushed design": 24,
  //   "Design digitization": 41,
  //   "SME involvement": 12,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Passive Safety Systems",
  //   "Subdivision": "Transmission",
  //   "Department": "Body design 1",
  //   "Manager": "Frank",
  //   "% Design Errors": 47,
  //   "% Schedule delays": 47,
  //   "% Cost overrun": 53,
  //   "Iterations per design": 0.3,
  //   "% Rushed design": 49,
  //   "Design digitization": 76,
  //   "SME involvement": 38,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Passive Safety Systems",
  //   "Subdivision": "Differential",
  //   "Department": "Body design 2",
  //   "Manager": "Ginevra",
  //   "% Design Errors": 13,
  //   "% Schedule delays": 41,
  //   "% Cost overrun": 38,
  //   "Iterations per design": 0,
  //   "% Rushed design": 38,
  //   "Design digitization": 20,
  //   "SME involvement": 80,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Passive Safety Systems",
  //   "Subdivision": "Braking",
  //   "Department": "Body design 3",
  //   "Manager": "Harold",
  //   "% Design Errors": 69,
  //   "% Schedule delays": 25,
  //   "% Cost overrun": 45,
  //   "Iterations per design": 4.8,
  //   "% Rushed design": 9,
  //   "Design digitization": 88,
  //   "SME involvement": 63,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Passive Safety Systems",
  //   "Subdivision": "Software",
  //   "Department": "Body design functional",
  //   "Manager": "Isabel",
  //   "% Design Errors": 79,
  //   "% Schedule delays": 67,
  //   "% Cost overrun": 19,
  //   "Iterations per design": 8,
  //   "% Rushed design": 93,
  //   "Design digitization": 69,
  //   "SME involvement": 91,
  //   "Predicted Design Errors": 3
  // },
  {
    "Business Unit": "Government",
    "Division": "Active Safety Systems",
    "Subdivision": "Foundation Brakes",
    "Department": "Body designseats",
    "Manager": "Thomas Nejman",
    "% Design Errors": 56,
    "% Schedule delays": 5,
    "% Cost overrun": 33,
    "Iterations per design": 2.5,
    "% Rushed design": 62,
    "Design digitization": 96,
    "SME involvement": 84,
    "Predicted Design Errors": 20
  },
  {
    "Business Unit": "Government",
    "Division": "Active Safety Systems",
    "Subdivision": "Brake Controls",
    "Department": "Engineering and data innovation",
    "Manager": "Henry Whiting",
    "% Design Errors": 44,
    "% Schedule delays": 93,
    "% Cost overrun": 66,
    "Iterations per design": 8.9,
    "% Rushed design": 90,
    "Design digitization": 12,
    "SME involvement": 70,
    "Predicted Design Errors": 24
  },
  {
    "Business Unit": "Government",
    "Division": "Active Safety Systems",
    "Subdivision": "EB100",
    "Department": "Engineering design chassis",
    "Manager": "Ryan Biehl",
    "% Design Errors": 69,
    "% Schedule delays": 96,
    "% Cost overrun": 66,
    "Iterations per design": 9.4,
    "% Rushed design": 48,
    "Design digitization": 72,
    "SME involvement": 51,
    "Predicted Design Errors": 13
  },
  {
    "Business Unit": "Government",
    "Division": "Active Safety Systems",
    "Subdivision": "Steering Systems",
    "Department": "Electronic systems 1",
    "Manager": "Theo Kaster",
    "% Design Errors": 74,
    "% Schedule delays": 38,
    "% Cost overrun": 32,
    "Iterations per design": 4.8,
    "% Rushed design": 18,
    "Design digitization": 79,
    "SME involvement": 19,
    "Predicted Design Errors": 14
  },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Active Safety Systems",
  //   "Subdivision": "Transmission",
  //   "Department": "Electronic system 2",
  //   "Manager": "Candice",
  //   "% Design Errors": 48,
  //   "% Schedule delays": 48,
  //   "% Cost overrun": 25,
  //   "Iterations per design": 3.5,
  //   "% Rushed design": 32,
  //   "Design digitization": 53,
  //   "SME involvement": 76,
  //   "Predicted Design Errors": 1
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Active Safety Systems",
  //   "Subdivision": "Differential",
  //   "Department": "Interior design 1",
  //   "Manager": "David",
  //   "% Design Errors": 36,
  //   "% Schedule delays": 3,
  //   "% Cost overrun": 70,
  //   "Iterations per design": 4.3,
  //   "% Rushed design": 65,
  //   "Design digitization": 96,
  //   "SME involvement": 37,
  //   "Predicted Design Errors": 3
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Active Safety Systems",
  //   "Subdivision": "Braking",
  //   "Department": "Integrated Vehicle systems",
  //   "Manager": "Eileen",
  //   "% Design Errors": 9,
  //   "% Schedule delays": 58,
  //   "% Cost overrun": 68,
  //   "Iterations per design": 5.3,
  //   "% Rushed design": 2,
  //   "Design digitization": 95,
  //   "SME involvement": 10,
  //   "Predicted Design Errors": 2
  // },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Active Safety Systems",
  //   "Subdivision": "Software",
  //   "Department": "Quality engineering",
  //   "Manager": "Frank",
  //   "% Design Errors": 36,
  //   "% Schedule delays": 0,
  //   "% Cost overrun": 53,
  //   "Iterations per design": 5.3,
  //   "% Rushed design": 73,
  //   "Design digitization": 82,
  //   "SME involvement": 95,
  //   "Predicted Design Errors": 1
  // },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Vehicle Dynamics & Control, Autonomous Driving",
    "Department": "Production engineering",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 66,
    "% Schedule delays": 5,
    "% Cost overrun": 89,
    "Iterations per design": 5.8,
    "% Rushed design": 22,
    "Design digitization": 56,
    "SME involvement": 3,
    "Predicted Design Errors": 10
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Driveline & Suspension Controls, Wheel End Solutions",
    "Department": "Vehicle Performance Dvelopment",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 59,
    "% Schedule delays": 59,
    "% Cost overrun": 65,
    "Iterations per design": 0.7,
    "% Rushed design": 90,
    "Design digitization": 31,
    "SME involvement": 33,
    "Predicted Design Errors": 8
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Vehicle Energy Management Systems",
    "Department": "Vehicle planning production engineering",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 99,
    "% Schedule delays": 15,
    "% Cost overrun": 75,
    "Iterations per design": 1.9,
    "% Rushed design": 42,
    "Design digitization": 56,
    "SME involvement": 48,
    "Predicted Design Errors": 24
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Fleet Solutions",
    "Department": "Body design 1",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 58,
    "% Schedule delays": 96,
    "% Cost overrun": 37,
    "Iterations per design": 9.4,
    "% Rushed design": 43,
    "Design digitization": 93,
    "SME involvement": 6,
    "Predicted Design Errors": 28
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Trailer Systems",
    "Department": "Body design 2",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 59,
    "% Schedule delays": 12,
    "% Cost overrun": 34,
    "Iterations per design": 6.4,
    "% Rushed design": 39,
    "Design digitization": 97,
    "SME involvement": 39,
    "Predicted Design Errors": 23
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Off-Highway Solutions",
    "Department": "Body design 3",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 15,
    "% Schedule delays": 48,
    "% Cost overrun": 49,
    "Iterations per design": 9.9,
    "% Rushed design": 59,
    "Design digitization": 100,
    "SME involvement": 53,
    "Predicted Design Errors": 2
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Car Systems",
    "Department": "Body design functional",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 26,
    "% Schedule delays": 9,
    "% Cost overrun": 48,
    "Iterations per design": 7.9,
    "% Rushed design": 23,
    "Design digitization": 59,
    "SME involvement": 33,
    "Predicted Design Errors": 11
  },
  // {
  //   "Business Unit": "Government",
  //   "Division": "Commercial Vehicle Control Systems",
  //   "Subdivision": "Software",
  //   "Department": "Body designseats",
  //   "Manager": "Candice",
  //   "% Design Errors": 84,
  //   "% Schedule delays": 9,
  //   "% Cost overrun": 30,
  //   "Iterations per design": 1.1,
  //   "% Rushed design": 11,
  //   "Design digitization": 24,
  //   "SME involvement": 80,
  //   "Predicted Design Errors": 1
  // },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Speeder",
//     "Subdivision": "Intake",
//     "Department": "Engineering and data innovation",
//     "Manager": "David",
//     "% Design Errors": 66,
//     "% Schedule delays": 4,
//     "% Cost overrun": 66,
//     "Iterations per design": 1.2,
//     "% Rushed design": 91,
//     "Design digitization": 88,
//     "SME involvement": 38,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Speeder",
//     "Subdivision": "Exhaust",
//     "Department": "Engineering design chassis",
//     "Manager": "Eileen",
//     "% Design Errors": 82,
//     "% Schedule delays": 26,
//     "% Cost overrun": 71,
//     "Iterations per design": 8.6,
//     "% Rushed design": 96,
//     "Design digitization": 93,
//     "SME involvement": 49,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Speeder",
//     "Subdivision": "Fuel",
//     "Department": "Electronic systems 1",
//     "Manager": "Frank",
//     "% Design Errors": 89,
//     "% Schedule delays": 30,
//     "% Cost overrun": 5,
//     "Iterations per design": 0.4,
//     "% Rushed design": 85,
//     "Design digitization": 20,
//     "SME involvement": 17,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Speeder",
//     "Subdivision": "Valve",
//     "Department": "Electronic system 2",
//     "Manager": "Ginevra",
//     "% Design Errors": 44,
//     "% Schedule delays": 54,
//     "% Cost overrun": 56,
//     "Iterations per design": 3.8,
//     "% Rushed design": 31,
//     "Design digitization": 70,
//     "SME involvement": 27,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Speeder",
//     "Subdivision": "Transmission",
//     "Department": "Interior design 1",
//     "Manager": "Harold",
//     "% Design Errors": 46,
//     "% Schedule delays": 84,
//     "% Cost overrun": 75,
//     "Iterations per design": 6.5,
//     "% Rushed design": 49,
//     "Design digitization": 82,
//     "SME involvement": 57,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Speeder",
//     "Subdivision": "Differential",
//     "Department": "Integrated Vehicle systems",
//     "Manager": "Isabel",
//     "% Design Errors": 69,
//     "% Schedule delays": 91,
//     "% Cost overrun": 27,
//     "Iterations per design": 6.5,
//     "% Rushed design": 12,
//     "Design digitization": 75,
//     "SME involvement": 92,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Speeder",
//     "Subdivision": "Braking",
//     "Department": "Quality engineering",
//     "Manager": "Jose",
//     "% Design Errors": 91,
//     "% Schedule delays": 21,
//     "% Cost overrun": 62,
//     "Iterations per design": 5.8,
//     "% Rushed design": 85,
//     "Design digitization": 72,
//     "SME involvement": 37,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Speeder",
//     "Subdivision": "Software",
//     "Department": "Production engineering",
//     "Manager": "Krishna",
//     "% Design Errors": 29,
//     "% Schedule delays": 0,
//     "% Cost overrun": 81,
//     "Iterations per design": 1,
//     "% Rushed design": 43,
//     "Design digitization": 90,
//     "SME involvement": 83,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "MaxDrive",
//     "Subdivision": "Intake",
//     "Department": "Vehicle Performance Dvelopment",
//     "Manager": "Anastasia",
//     "% Design Errors": 29,
//     "% Schedule delays": 22,
//     "% Cost overrun": 73,
//     "Iterations per design": 9.8,
//     "% Rushed design": 37,
//     "Design digitization": 33,
//     "SME involvement": 30,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "MaxDrive",
//     "Subdivision": "Exhaust",
//     "Department": "Vehicle planning production engineering",
//     "Manager": "Bart",
//     "% Design Errors": 99,
//     "% Schedule delays": 43,
//     "% Cost overrun": 58,
//     "Iterations per design": 5.1,
//     "% Rushed design": 50,
//     "Design digitization": 68,
//     "SME involvement": 37,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "MaxDrive",
//     "Subdivision": "Fuel",
//     "Department": "Body design 1",
//     "Manager": "Candice",
//     "% Design Errors": 63,
//     "% Schedule delays": 88,
//     "% Cost overrun": 62,
//     "Iterations per design": 5.5,
//     "% Rushed design": 98,
//     "Design digitization": 84,
//     "SME involvement": 29,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "MaxDrive",
//     "Subdivision": "Valve",
//     "Department": "Body design 2",
//     "Manager": "David",
//     "% Design Errors": 52,
//     "% Schedule delays": 29,
//     "% Cost overrun": 14,
//     "Iterations per design": 0.8,
//     "% Rushed design": 64,
//     "Design digitization": 29,
//     "SME involvement": 30,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "MaxDrive",
//     "Subdivision": "Transmission",
//     "Department": "Body design 3",
//     "Manager": "Eileen",
//     "% Design Errors": 98,
//     "% Schedule delays": 27,
//     "% Cost overrun": 74,
//     "Iterations per design": 2.9,
//     "% Rushed design": 15,
//     "Design digitization": 89,
//     "SME involvement": 74,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "MaxDrive",
//     "Subdivision": "Differential",
//     "Department": "Body design functional",
//     "Manager": "Frank",
//     "% Design Errors": 67,
//     "% Schedule delays": 89,
//     "% Cost overrun": 10,
//     "Iterations per design": 0.1,
//     "% Rushed design": 76,
//     "Design digitization": 82,
//     "SME involvement": 48,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "MaxDrive",
//     "Subdivision": "Braking",
//     "Department": "Body designseats",
//     "Manager": "Ginevra",
//     "% Design Errors": 27,
//     "% Schedule delays": 82,
//     "% Cost overrun": 72,
//     "Iterations per design": 0.7,
//     "% Rushed design": 96,
//     "Design digitization": 9,
//     "SME involvement": 61,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "MaxDrive",
//     "Subdivision": "Software",
//     "Department": "Engineering and data innovation",
//     "Manager": "Harold",
//     "% Design Errors": 88,
//     "% Schedule delays": 5,
//     "% Cost overrun": 88,
//     "Iterations per design": 9.1,
//     "% Rushed design": 56,
//     "Design digitization": 52,
//     "SME involvement": 98,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "TireSwell",
//     "Subdivision": "Intake",
//     "Department": "Engineering design chassis",
//     "Manager": "Isabel",
//     "% Design Errors": 7,
//     "% Schedule delays": 23,
//     "% Cost overrun": 36,
//     "Iterations per design": 0.2,
//     "% Rushed design": 80,
//     "Design digitization": 35,
//     "SME involvement": 67,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "TireSwell",
//     "Subdivision": "Exhaust",
//     "Department": "Electronic systems 1",
//     "Manager": "Jose",
//     "% Design Errors": 77,
//     "% Schedule delays": 80,
//     "% Cost overrun": 72,
//     "Iterations per design": 2.1,
//     "% Rushed design": 70,
//     "Design digitization": 13,
//     "SME involvement": 64,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "TireSwell",
//     "Subdivision": "Fuel",
//     "Department": "Electronic system 2",
//     "Manager": "Krishna",
//     "% Design Errors": 97,
//     "% Schedule delays": 49,
//     "% Cost overrun": 14,
//     "Iterations per design": 4.3,
//     "% Rushed design": 36,
//     "Design digitization": 49,
//     "SME involvement": 20,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "TireSwell",
//     "Subdivision": "Valve",
//     "Department": "Interior design 1",
//     "Manager": "Anastasia",
//     "% Design Errors": 13,
//     "% Schedule delays": 4,
//     "% Cost overrun": 16,
//     "Iterations per design": 9,
//     "% Rushed design": 18,
//     "Design digitization": 42,
//     "SME involvement": 34,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "TireSwell",
//     "Subdivision": "Transmission",
//     "Department": "Integrated Vehicle systems",
//     "Manager": "Bart",
//     "% Design Errors": 32,
//     "% Schedule delays": 93,
//     "% Cost overrun": 40,
//     "Iterations per design": 8,
//     "% Rushed design": 4,
//     "Design digitization": 22,
//     "SME involvement": 81,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "TireSwell",
//     "Subdivision": "Differential",
//     "Department": "Quality engineering",
//     "Manager": "Candice",
//     "% Design Errors": 78,
//     "% Schedule delays": 12,
//     "% Cost overrun": 41,
//     "Iterations per design": 5.8,
//     "% Rushed design": 31,
//     "Design digitization": 78,
//     "SME involvement": 29,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "TireSwell",
//     "Subdivision": "Braking",
//     "Department": "Production engineering",
//     "Manager": "David",
//     "% Design Errors": 49,
//     "% Schedule delays": 6,
//     "% Cost overrun": 29,
//     "Iterations per design": 9.4,
//     "% Rushed design": 42,
//     "Design digitization": 2,
//     "SME involvement": 57,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "TireSwell",
//     "Subdivision": "Software",
//     "Department": "Vehicle Performance Dvelopment",
//     "Manager": "Eileen",
//     "% Design Errors": 12,
//     "% Schedule delays": 28,
//     "% Cost overrun": 87,
//     "Iterations per design": 4.6,
//     "% Rushed design": 2,
//     "Design digitization": 36,
//     "SME involvement": 28,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SportsStar",
//     "Subdivision": "Intake",
//     "Department": "Vehicle planning production engineering",
//     "Manager": "Frank",
//     "% Design Errors": 12,
//     "% Schedule delays": 10,
//     "% Cost overrun": 55,
//     "Iterations per design": 4.1,
//     "% Rushed design": 37,
//     "Design digitization": 55,
//     "SME involvement": 84,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SportsStar",
//     "Subdivision": "Exhaust",
//     "Department": "Body design 1",
//     "Manager": "Ginevra",
//     "% Design Errors": 9,
//     "% Schedule delays": 69,
//     "% Cost overrun": 62,
//     "Iterations per design": 2.1,
//     "% Rushed design": 25,
//     "Design digitization": 94,
//     "SME involvement": 36,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SportsStar",
//     "Subdivision": "Fuel",
//     "Department": "Body design 2",
//     "Manager": "Harold",
//     "% Design Errors": 39,
//     "% Schedule delays": 94,
//     "% Cost overrun": 94,
//     "Iterations per design": 5.6,
//     "% Rushed design": 59,
//     "Design digitization": 76,
//     "SME involvement": 32,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SportsStar",
//     "Subdivision": "Valve",
//     "Department": "Body design 3",
//     "Manager": "Isabel",
//     "% Design Errors": 36,
//     "% Schedule delays": 62,
//     "% Cost overrun": 10,
//     "Iterations per design": 0.6,
//     "% Rushed design": 70,
//     "Design digitization": 4,
//     "SME involvement": 23,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SportsStar",
//     "Subdivision": "Transmission",
//     "Department": "Body design functional",
//     "Manager": "Jose",
//     "% Design Errors": 60,
//     "% Schedule delays": 23,
//     "% Cost overrun": 45,
//     "Iterations per design": 8.1,
//     "% Rushed design": 67,
//     "Design digitization": 61,
//     "SME involvement": 68,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SportsStar",
//     "Subdivision": "Differential",
//     "Department": "Body designseats",
//     "Manager": "Krishna",
//     "% Design Errors": 18,
//     "% Schedule delays": 64,
//     "% Cost overrun": 18,
//     "Iterations per design": 8.2,
//     "% Rushed design": 79,
//     "Design digitization": 10,
//     "SME involvement": 70,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SportsStar",
//     "Subdivision": "Braking",
//     "Department": "Engineering and data innovation",
//     "Manager": "Anastasia",
//     "% Design Errors": 65,
//     "% Schedule delays": 2,
//     "% Cost overrun": 7,
//     "Iterations per design": 2.8,
//     "% Rushed design": 20,
//     "Design digitization": 36,
//     "SME involvement": 27,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SportsStar",
//     "Subdivision": "Software",
//     "Department": "Engineering design chassis",
//     "Manager": "Bart",
//     "% Design Errors": 80,
//     "% Schedule delays": 43,
//     "% Cost overrun": 15,
//     "Iterations per design": 1.9,
//     "% Rushed design": 3,
//     "Design digitization": 38,
//     "SME involvement": 39,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "AirZoom",
//     "Subdivision": "Intake",
//     "Department": "Electronic systems 1",
//     "Manager": "Candice",
//     "% Design Errors": 24,
//     "% Schedule delays": 30,
//     "% Cost overrun": 64,
//     "Iterations per design": 1.6,
//     "% Rushed design": 71,
//     "Design digitization": 36,
//     "SME involvement": 8,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "AirZoom",
//     "Subdivision": "Exhaust",
//     "Department": "Electronic system 2",
//     "Manager": "David",
//     "% Design Errors": 23,
//     "% Schedule delays": 77,
//     "% Cost overrun": 10,
//     "Iterations per design": 6,
//     "% Rushed design": 21,
//     "Design digitization": 98,
//     "SME involvement": 16,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "AirZoom",
//     "Subdivision": "Fuel",
//     "Department": "Interior design 1",
//     "Manager": "Eileen",
//     "% Design Errors": 68,
//     "% Schedule delays": 22,
//     "% Cost overrun": 7,
//     "Iterations per design": 2,
//     "% Rushed design": 82,
//     "Design digitization": 78,
//     "SME involvement": 46,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "AirZoom",
//     "Subdivision": "Valve",
//     "Department": "Integrated Vehicle systems",
//     "Manager": "Frank",
//     "% Design Errors": 56,
//     "% Schedule delays": 98,
//     "% Cost overrun": 5,
//     "Iterations per design": 3.5,
//     "% Rushed design": 55,
//     "Design digitization": 29,
//     "SME involvement": 47,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "AirZoom",
//     "Subdivision": "Transmission",
//     "Department": "Quality engineering",
//     "Manager": "Ginevra",
//     "% Design Errors": 13,
//     "% Schedule delays": 84,
//     "% Cost overrun": 65,
//     "Iterations per design": 4,
//     "% Rushed design": 1,
//     "Design digitization": 22,
//     "SME involvement": 12,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "AirZoom",
//     "Subdivision": "Differential",
//     "Department": "Production engineering",
//     "Manager": "Harold",
//     "% Design Errors": 77,
//     "% Schedule delays": 91,
//     "% Cost overrun": 87,
//     "Iterations per design": 4.3,
//     "% Rushed design": 22,
//     "Design digitization": 86,
//     "SME involvement": 72,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "AirZoom",
//     "Subdivision": "Braking",
//     "Department": "Vehicle Performance Dvelopment",
//     "Manager": "Isabel",
//     "% Design Errors": 92,
//     "% Schedule delays": 47,
//     "% Cost overrun": 16,
//     "Iterations per design": 9.6,
//     "% Rushed design": 35,
//     "Design digitization": 27,
//     "SME involvement": 53,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "AirZoom",
//     "Subdivision": "Software",
//     "Department": "Vehicle planning production engineering",
//     "Manager": "Jose",
//     "% Design Errors": 16,
//     "% Schedule delays": 38,
//     "% Cost overrun": 50,
//     "Iterations per design": 8.1,
//     "% Rushed design": 8,
//     "Design digitization": 65,
//     "SME involvement": 8,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Roadrunner",
//     "Subdivision": "Intake",
//     "Department": "Body design 1",
//     "Manager": "Anastasia",
//     "% Design Errors": 78,
//     "% Schedule delays": 87,
//     "% Cost overrun": 61,
//     "Iterations per design": 6.9,
//     "% Rushed design": 96,
//     "Design digitization": 25,
//     "SME involvement": 74,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Roadrunner",
//     "Subdivision": "Exhaust",
//     "Department": "Body design 2",
//     "Manager": "Bart",
//     "% Design Errors": 70,
//     "% Schedule delays": 17,
//     "% Cost overrun": 49,
//     "Iterations per design": 3.8,
//     "% Rushed design": 69,
//     "Design digitization": 64,
//     "SME involvement": 99,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Roadrunner",
//     "Subdivision": "Fuel",
//     "Department": "Body design 3",
//     "Manager": "Candice",
//     "% Design Errors": 11,
//     "% Schedule delays": 49,
//     "% Cost overrun": 31,
//     "Iterations per design": 7.9,
//     "% Rushed design": 53,
//     "Design digitization": 52,
//     "SME involvement": 5,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Roadrunner",
//     "Subdivision": "Valve",
//     "Department": "Body design functional",
//     "Manager": "David",
//     "% Design Errors": 31,
//     "% Schedule delays": 61,
//     "% Cost overrun": 50,
//     "Iterations per design": 8.3,
//     "% Rushed design": 80,
//     "Design digitization": 42,
//     "SME involvement": 92,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Roadrunner",
//     "Subdivision": "Transmission",
//     "Department": "Body designseats",
//     "Manager": "Eileen",
//     "% Design Errors": 40,
//     "% Schedule delays": 38,
//     "% Cost overrun": 98,
//     "Iterations per design": 5.9,
//     "% Rushed design": 58,
//     "Design digitization": 78,
//     "SME involvement": 82,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Roadrunner",
//     "Subdivision": "Differential",
//     "Department": "Engineering and data innovation",
//     "Manager": "Frank",
//     "% Design Errors": 59,
//     "% Schedule delays": 33,
//     "% Cost overrun": 63,
//     "Iterations per design": 0.8,
//     "% Rushed design": 7,
//     "Design digitization": 73,
//     "SME involvement": 22,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Roadrunner",
//     "Subdivision": "Braking",
//     "Department": "Engineering design chassis",
//     "Manager": "Ginevra",
//     "% Design Errors": 35,
//     "% Schedule delays": 92,
//     "% Cost overrun": 15,
//     "Iterations per design": 1.3,
//     "% Rushed design": 33,
//     "Design digitization": 21,
//     "SME involvement": 23,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Roadrunner",
//     "Subdivision": "Software",
//     "Department": "Electronic systems 1",
//     "Manager": "Harold",
//     "% Design Errors": 58,
//     "% Schedule delays": 59,
//     "% Cost overrun": 65,
//     "Iterations per design": 0.9,
//     "% Rushed design": 35,
//     "Design digitization": 4,
//     "SME involvement": 96,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Canvas",
//     "Subdivision": "Intake",
//     "Department": "Electronic system 2",
//     "Manager": "Isabel",
//     "% Design Errors": 16,
//     "% Schedule delays": 75,
//     "% Cost overrun": 6,
//     "Iterations per design": 7.5,
//     "% Rushed design": 2,
//     "Design digitization": 57,
//     "SME involvement": 95,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Canvas",
//     "Subdivision": "Exhaust",
//     "Department": "Interior design 1",
//     "Manager": "Jose",
//     "% Design Errors": 13,
//     "% Schedule delays": 55,
//     "% Cost overrun": 38,
//     "Iterations per design": 0,
//     "% Rushed design": 26,
//     "Design digitization": 16,
//     "SME involvement": 57,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Canvas",
//     "Subdivision": "Fuel",
//     "Department": "Integrated Vehicle systems",
//     "Manager": "Anastasia",
//     "% Design Errors": 36,
//     "% Schedule delays": 4,
//     "% Cost overrun": 39,
//     "Iterations per design": 8.5,
//     "% Rushed design": 11,
//     "Design digitization": 95,
//     "SME involvement": 99,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Canvas",
//     "Subdivision": "Valve",
//     "Department": "Quality engineering",
//     "Manager": "Anastasia",
//     "% Design Errors": 59,
//     "% Schedule delays": 96,
//     "% Cost overrun": 57,
//     "Iterations per design": 3,
//     "% Rushed design": 53,
//     "Design digitization": 21,
//     "SME involvement": 29,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Canvas",
//     "Subdivision": "Transmission",
//     "Department": "Production engineering",
//     "Manager": "Candice",
//     "% Design Errors": 10,
//     "% Schedule delays": 26,
//     "% Cost overrun": 38,
//     "Iterations per design": 8.5,
//     "% Rushed design": 6,
//     "Design digitization": 32,
//     "SME involvement": 41,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Canvas",
//     "Subdivision": "Differential",
//     "Department": "Vehicle Performance Dvelopment",
//     "Manager": "David",
//     "% Design Errors": 76,
//     "% Schedule delays": 49,
//     "% Cost overrun": 42,
//     "Iterations per design": 3.1,
//     "% Rushed design": 72,
//     "Design digitization": 100,
//     "SME involvement": 17,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Canvas",
//     "Subdivision": "Braking",
//     "Department": "Vehicle planning production engineering",
//     "Manager": "Eileen",
//     "% Design Errors": 96,
//     "% Schedule delays": 90,
//     "% Cost overrun": 4,
//     "Iterations per design": 9.8,
//     "% Rushed design": 50,
//     "Design digitization": 68,
//     "SME involvement": 48,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Canvas",
//     "Subdivision": "Software",
//     "Department": "Body design 1",
//     "Manager": "Frank",
//     "% Design Errors": 45,
//     "% Schedule delays": 50,
//     "% Cost overrun": 97,
//     "Iterations per design": 9.9,
//     "% Rushed design": 30,
//     "Design digitization": 53,
//     "SME involvement": 1,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Passive Safety Systems 10+",
//     "Subdivision": "Intake",
//     "Department": "Body design 2",
//     "Manager": "Ginevra",
//     "% Design Errors": 53,
//     "% Schedule delays": 35,
//     "% Cost overrun": 64,
//     "Iterations per design": 8,
//     "% Rushed design": 87,
//     "Design digitization": 66,
//     "SME involvement": 85,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Passive Safety Systems 10+",
//     "Subdivision": "Exhaust",
//     "Department": "Body design 3",
//     "Manager": "Harold",
//     "% Design Errors": 98,
//     "% Schedule delays": 14,
//     "% Cost overrun": 99,
//     "Iterations per design": 7.4,
//     "% Rushed design": 90,
//     "Design digitization": 15,
//     "SME involvement": 91,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Passive Safety Systems 10+",
//     "Subdivision": "Fuel",
//     "Department": "Body design functional",
//     "Manager": "Isabel",
//     "% Design Errors": 77,
//     "% Schedule delays": 27,
//     "% Cost overrun": 70,
//     "Iterations per design": 7.7,
//     "% Rushed design": 12,
//     "Design digitization": 34,
//     "SME involvement": 99,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Passive Safety Systems 10+",
//     "Subdivision": "Valve",
//     "Department": "Body designseats",
//     "Manager": "Jose",
//     "% Design Errors": 32,
//     "% Schedule delays": 9,
//     "% Cost overrun": 90,
//     "Iterations per design": 5.1,
//     "% Rushed design": 22,
//     "Design digitization": 70,
//     "SME involvement": 68,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Passive Safety Systems 10+",
//     "Subdivision": "Transmission",
//     "Department": "Engineering and data innovation",
//     "Manager": "Anastasia",
//     "% Design Errors": 45,
//     "% Schedule delays": 84,
//     "% Cost overrun": 73,
//     "Iterations per design": 0.9,
//     "% Rushed design": 80,
//     "Design digitization": 9,
//     "SME involvement": 86,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Passive Safety Systems 10+",
//     "Subdivision": "Differential",
//     "Department": "Engineering design chassis",
//     "Manager": "Bart",
//     "% Design Errors": 16,
//     "% Schedule delays": 43,
//     "% Cost overrun": 84,
//     "Iterations per design": 9.1,
//     "% Rushed design": 45,
//     "Design digitization": 32,
//     "SME involvement": 91,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Passive Safety Systems 10+",
//     "Subdivision": "Braking",
//     "Department": "Electronic systems 1",
//     "Manager": "Candice",
//     "% Design Errors": 93,
//     "% Schedule delays": 16,
//     "% Cost overrun": 15,
//     "Iterations per design": 3.4,
//     "% Rushed design": 8,
//     "Design digitization": 86,
//     "SME involvement": 18,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "Passive Safety Systems 10+",
//     "Subdivision": "Software",
//     "Department": "Electronic system 2",
//     "Manager": "David",
//     "% Design Errors": 3,
//     "% Schedule delays": 72,
//     "% Cost overrun": 22,
//     "Iterations per design": 2.8,
//     "% Rushed design": 37,
//     "Design digitization": 54,
//     "SME involvement": 82,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "VaultSafe",
//     "Subdivision": "Intake",
//     "Department": "Interior design 1",
//     "Manager": "Eileen",
//     "% Design Errors": 30,
//     "% Schedule delays": 30,
//     "% Cost overrun": 76,
//     "Iterations per design": 0,
//     "% Rushed design": 22,
//     "Design digitization": 9,
//     "SME involvement": 77,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "VaultSafe",
//     "Subdivision": "Exhaust",
//     "Department": "Integrated Vehicle systems",
//     "Manager": "Frank",
//     "% Design Errors": 24,
//     "% Schedule delays": 18,
//     "% Cost overrun": 96,
//     "Iterations per design": 7.7,
//     "% Rushed design": 69,
//     "Design digitization": 0,
//     "SME involvement": 4,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "VaultSafe",
//     "Subdivision": "Fuel",
//     "Department": "Quality engineering",
//     "Manager": "Ginevra",
//     "% Design Errors": 51,
//     "% Schedule delays": 11,
//     "% Cost overrun": 37,
//     "Iterations per design": 7.2,
//     "% Rushed design": 8,
//     "Design digitization": 20,
//     "SME involvement": 67,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "VaultSafe",
//     "Subdivision": "Valve",
//     "Department": "Production engineering",
//     "Manager": "Harold",
//     "% Design Errors": 27,
//     "% Schedule delays": 3,
//     "% Cost overrun": 89,
//     "Iterations per design": 1.2,
//     "% Rushed design": 43,
//     "Design digitization": 89,
//     "SME involvement": 47,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "VaultSafe",
//     "Subdivision": "Transmission",
//     "Department": "Vehicle Performance Dvelopment",
//     "Manager": "Isabel",
//     "% Design Errors": 32,
//     "% Schedule delays": 48,
//     "% Cost overrun": 71,
//     "Iterations per design": 4.3,
//     "% Rushed design": 18,
//     "Design digitization": 98,
//     "SME involvement": 72,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "VaultSafe",
//     "Subdivision": "Differential",
//     "Department": "Vehicle planning production engineering",
//     "Manager": "Jose",
//     "% Design Errors": 72,
//     "% Schedule delays": 84,
//     "% Cost overrun": 32,
//     "Iterations per design": 9.5,
//     "% Rushed design": 6,
//     "Design digitization": 20,
//     "SME involvement": 17,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "VaultSafe",
//     "Subdivision": "Braking",
//     "Department": "Body design 1",
//     "Manager": "Krishna",
//     "% Design Errors": 30,
//     "% Schedule delays": 82,
//     "% Cost overrun": 32,
//     "Iterations per design": 8.9,
//     "% Rushed design": 98,
//     "Design digitization": 52,
//     "SME involvement": 48,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "VaultSafe",
//     "Subdivision": "Software",
//     "Department": "Body design 2",
//     "Manager": "Anastasia",
//     "% Design Errors": 96,
//     "% Schedule delays": 16,
//     "% Cost overrun": 39,
//     "Iterations per design": 1.7,
//     "% Rushed design": 91,
//     "Design digitization": 58,
//     "SME involvement": 13,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SteerStar",
//     "Subdivision": "Intake",
//     "Department": "Body design 3",
//     "Manager": "Bart",
//     "% Design Errors": 0,
//     "% Schedule delays": 60,
//     "% Cost overrun": 87,
//     "Iterations per design": 3.8,
//     "% Rushed design": 93,
//     "Design digitization": 16,
//     "SME involvement": 31,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SteerStar",
//     "Subdivision": "Exhaust",
//     "Department": "Body design functional",
//     "Manager": "Candice",
//     "% Design Errors": 82,
//     "% Schedule delays": 85,
//     "% Cost overrun": 53,
//     "Iterations per design": 1.7,
//     "% Rushed design": 92,
//     "Design digitization": 93,
//     "SME involvement": 12,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SteerStar",
//     "Subdivision": "Fuel",
//     "Department": "Body designseats",
//     "Manager": "David",
//     "% Design Errors": 59,
//     "% Schedule delays": 53,
//     "% Cost overrun": 47,
//     "Iterations per design": 6.7,
//     "% Rushed design": 88,
//     "Design digitization": 56,
//     "SME involvement": 6,
//     "Predicted Design Errors": 1
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SteerStar",
//     "Subdivision": "Valve",
//     "Department": "Engineering and data innovation",
//     "Manager": "Eileen",
//     "% Design Errors": 86,
//     "% Schedule delays": 9,
//     "% Cost overrun": 78,
//     "Iterations per design": 5.8,
//     "% Rushed design": 61,
//     "Design digitization": 79,
//     "SME involvement": 86,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SteerStar",
//     "Subdivision": "Transmission",
//     "Department": "Engineering design chassis",
//     "Manager": "Frank",
//     "% Design Errors": 38,
//     "% Schedule delays": 33,
//     "% Cost overrun": 79,
//     "Iterations per design": 8.8,
//     "% Rushed design": 16,
//     "Design digitization": 48,
//     "SME involvement": 74,
//     "Predicted Design Errors": 2
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SteerStar",
//     "Subdivision": "Differential",
//     "Department": "Electronic systems 1",
//     "Manager": "Ginevra",
//     "% Design Errors": 74,
//     "% Schedule delays": 15,
//     "% Cost overrun": 42,
//     "Iterations per design": 5.9,
//     "% Rushed design": 87,
//     "Design digitization": 51,
//     "SME involvement": 23,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SteerStar",
//     "Subdivision": "Braking",
//     "Department": "Electronic system 2",
//     "Manager": "Harold",
//     "% Design Errors": 16,
//     "% Schedule delays": 4,
//     "% Cost overrun": 31,
//     "Iterations per design": 3.6,
//     "% Rushed design": 91,
//     "Design digitization": 99,
//     "SME involvement": 36,
//     "Predicted Design Errors": 3
//   },
//   {
//     "Business Unit": "Bespoke",
//     "Division": "SteerStar",
//     "Subdivision": "Software",
//     "Department": "Interior design 1",
//     "Manager": "Isabel",
//     "% Design Errors": 71,
//     "% Schedule delays": 96,
//     "% Cost overrun": 40,
//     "Iterations per design": 8.6,
//     "% Rushed design": 76,
//     "Design digitization": 35,
//     "SME involvement": 54,
//     "Predicted Design Errors": 1
//   }
]