export const dataScreen1 = [
  {
    "Business Unit": "Commercial",
    "Division": "Car Powertrain Technology",
    "Subdivision": "Automatic Transmissions",
    "Department": "Body design 1",
    "Manager": "Markus Schwabe",
    "% Design Errors": 90,
    "% Schedule delays": 34,
    "% Cost overrun": 11,
    "Iterations per design": 7.8,
    "% Rushed design": 31,
    "Design digitization": 81,
    "SME involvement": 34,
    "Predicted Design Errors": 7
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Powertrain Technology",
    "Subdivision": "Dual Clutch & Manual Transmissions",
    "Department": "Body design 2",
    "Manager": "Markus Schmidt",
    "% Design Errors": 53,
    "% Schedule delays": 65,
    "% Cost overrun": 65,
    "Iterations per design": 0.7,
    "% Rushed design": 24,
    "Design digitization": 41,
    "SME involvement": 23,
    "Predicted Design Errors": 8
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Powertrain Technology",
    "Subdivision": "Powertrain Modules",
    "Department": "Body design 3",
    "Manager": "Claus Umnus",
    "% Design Errors": 40,
    "% Schedule delays": 21,
    "% Cost overrun": 18,
    "Iterations per design": 4.9,
    "% Rushed design": 34,
    "Design digitization": 97,
    "SME involvement": 30,
    "Predicted Design Errors": 14
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Chassis Technology",
    "Subdivision": "Chassis Systems & Modules",
    "Department": "Electronic system 2",
    "Manager": "Matthias Raulf",
    "% Design Errors": 62,
    "% Schedule delays": 70,
    "% Cost overrun": 12,
    "Iterations per design": 4.5,
    "% Rushed design": 12,
    "Design digitization": 68,
    "SME involvement": 33,
    "Predicted Design Errors": 15
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Chassis Technology",
    "Subdivision": "Chassis Components",
    "Department": "Interior design 1",
    "Manager": "Steffen Reichelt",
    "% Design Errors": 82,
    "% Schedule delays": 65,
    "% Cost overrun": 10,
    "Iterations per design": 8.7,
    "% Rushed design": 62,
    "Design digitization": 75,
    "SME involvement": 32,
    "Predicted Design Errors": 12
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Chassis Technology",
    "Subdivision": "Suspension Technology",
    "Department": "Integrated Vehicle systems",
    "Manager": "Mario Sabel",
    "% Design Errors": 9,
    "% Schedule delays": 20,
    "% Cost overrun": 55,
    "Iterations per design": 8.9,
    "% Rushed design": 63,
    "Design digitization": 19,
    "SME involvement": 38,
    "Predicted Design Errors": 30
  },
  {
    "Business Unit": "Commercial",
    "Division": "Car Chassis Technology",
    "Subdivision": "Chassis Actuators",
    "Department": "Quality engineering",
    "Manager": "Ingo Hermansa",
    "% Design Errors": 43,
    "% Schedule delays": 10,
    "% Cost overrun": 43,
    "Iterations per design": 6.2,
    "% Rushed design": 60,
    "Design digitization": 54,
    "SME involvement": 62,
    "Predicted Design Errors": 2
  },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "Truck & Van Driveline Technology",
    "Department": "Body design 2",
    "Manager": "Winfried Gründler",
    "% Design Errors": 46,
    "% Schedule delays": 16,
    "% Cost overrun": 63,
    "Iterations per design": 5.4,
    "% Rushed design": 58,
    "Design digitization": 51,
    "SME involvement": 66,
    "Predicted Design Errors": 19
  },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "Axle & Transmission System for Buses & Coaches",
    "Department": "Body design 3",
    "Manager": "Dr. Andreas Grossl",
    "% Design Errors": 7,
    "% Schedule delays": 37,
    "% Cost overrun": 30,
    "Iterations per design": 9.8,
    "% Rushed design": 24,
    "Design digitization": 55,
    "SME involvement": 34,
    "Predicted Design Errors": 30
  },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "CV Chassis Technology",
    "Department": "Body design functional",
    "Manager": "Joachim Holzner",
    "% Design Errors": 40,
    "% Schedule delays": 72,
    "% Cost overrun": 42,
    "Iterations per design": 4.7,
    "% Rushed design": 15,
    "Design digitization": 67,
    "SME involvement": 95,
    "Predicted Design Errors": 8
  },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "CV Powertrain Modules",
    "Department": "Body designseats",
    "Manager": "Kleber Barros Vinhas",
    "% Design Errors": 34,
    "% Schedule delays": 78,
    "% Cost overrun": 18,
    "Iterations per design": 7,
    "% Rushed design": 68,
    "Design digitization": 7,
    "SME involvement": 28,
    "Predicted Design Errors": 5
  },
  {
    "Business Unit": "Commercial",
    "Division": "Commercial Vehicle Technology",
    "Subdivision": "CV Steering Systems",
    "Department": "Engineering and data innovation",
    "Manager": "Tomas Bozek",
    "% Design Errors": 81,
    "% Schedule delays": 25,
    "% Cost overrun": 8,
    "Iterations per design": 9.8,
    "% Rushed design": 42,
    "Design digitization": 58,
    "SME involvement": 54,
    "Predicted Design Errors": 6
  },
  {
    "Business Unit": "Commercial",
    "Division": "Industrial Technology",
    "Subdivision": "Off-Highway & Test Systems",
    "Department": "Interior design 1",
    "Manager": "Udo Kneitz",
    "% Design Errors": 3,
    "% Schedule delays": 58,
    "% Cost overrun": 33,
    "Iterations per design": 1.2,
    "% Rushed design": 30,
    "Design digitization": 34,
    "SME involvement": 16,
    "Predicted Design Errors": 5
  },
  {
    "Business Unit": "Commercial",
    "Division": "Industrial Technology",
    "Subdivision": "Aviation Technology",
    "Department": "Integrated Vehicle systems",
    "Manager": "David",
    "% Design Errors": 85,
    "% Schedule delays": 46,
    "% Cost overrun": 33,
    "Iterations per design": 4.7,
    "% Rushed design": 17,
    "Design digitization": 36,
    "SME involvement": 52,
    "Predicted Design Errors": 9
  },
  {
    "Business Unit": "Commercial",
    "Division": "Industrial Technology",
    "Subdivision": "Marine & Special Driveline Technology",
    "Department": "Quality engineering",
    "Manager": "Daniel Härter",
    "% Design Errors": 16,
    "% Schedule delays": 35,
    "% Cost overrun": 82,
    "Iterations per design": 3.7,
    "% Rushed design": 51,
    "Design digitization": 54,
    "SME involvement": 43,
    "Predicted Design Errors": 20
  },
  {
    "Business Unit": "Commercial",
    "Division": "Industrial Technology",
    "Subdivision": "Wind Power Technology & Industrial Drives",
    "Department": "Production engineering",
    "Manager": "Udo Kneitz",
    "% Design Errors": 19,
    "% Schedule delays": 32,
    "% Cost overrun": 60,
    "Iterations per design": 5.9,
    "% Rushed design": 10,
    "Design digitization": 59,
    "SME involvement": 46,
    "Predicted Design Errors": 30
  },
  {
    "Business Unit": "Commercial",
    "Division": "E-Mobility",
    "Subdivision": "Electronic Systems",
    "Department": "Body design 3",
    "Manager": "Harald Deiss",
    "% Design Errors": 2,
    "% Schedule delays": 55,
    "% Cost overrun": 85,
    "Iterations per design": 7.3,
    "% Rushed design": 92,
    "Design digitization": 33,
    "SME involvement": 74,
    "Predicted Design Errors": 16
  },
  {
    "Business Unit": "Commercial",
    "Division": "E-Mobility",
    "Subdivision": "Electric Traction Drive",
    "Department": "Body design functional",
    "Manager": "Dr. Andreas Fink",
    "% Design Errors": 58,
    "% Schedule delays": 94,
    "% Cost overrun": 73,
    "Iterations per design": 7.4,
    "% Rushed design": 30,
    "Design digitization": 8,
    "SME involvement": 91,
    "Predicted Design Errors": 18
  },
  {
    "Business Unit": "Commercial",
    "Division": "E-Mobility",
    "Subdivision": "Axle Drives",
    "Department": "Body designseats",
    "Manager": "Kay Schmidt",
    "% Design Errors": 37,
    "% Schedule delays": 25,
    "% Cost overrun": 93,
    "Iterations per design": 4,
    "% Rushed design": 35,
    "Design digitization": 66,
    "SME involvement": 29,
    "Predicted Design Errors": 20
  },
  {
    "Business Unit": "Commercial",
    "Division": "E-Mobility",
    "Subdivision": "Electronic Interfaces",
    "Department": "Engineering and data innovation",
    "Manager": "Thomas Buda",
    "% Design Errors": 27,
    "% Schedule delays": 92,
    "% Cost overrun": 73,
    "Iterations per design": 2.8,
    "% Rushed design": 52,
    "Design digitization": 34,
    "SME involvement": 64,
    "Predicted Design Errors": 9
  },
  {
    "Business Unit": "Government",
    "Division": "Aftermarket",
    "Subdivision": "Independent Aftermarket",
    "Department": "Integrated Vehicle systems",
    "Manager": "Harold",
    "% Design Errors": 50,
    "% Schedule delays": 95,
    "% Cost overrun": 4,
    "Iterations per design": 8.1,
    "% Rushed design": 19,
    "Design digitization": 44,
    "SME involvement": 83,
    "Predicted Design Errors": 5
  },
  {
    "Business Unit": "Government",
    "Division": "Aftermarket",
    "Subdivision": "Original Equipment Supplier/Specific Original Equipment",
    "Department": "Quality engineering",
    "Manager": "Isabel",
    "% Design Errors": 1,
    "% Schedule delays": 26,
    "% Cost overrun": 6,
    "Iterations per design": 2.4,
    "% Rushed design": 14,
    "Design digitization": 60,
    "SME involvement": 33,
    "Predicted Design Errors": 12
  },
  {
    "Business Unit": "Government",
    "Division": "Aftermarket",
    "Subdivision": "Manufacturing",
    "Department": "Production engineering",
    "Manager": "Jose",
    "% Design Errors": 45,
    "% Schedule delays": 19,
    "% Cost overrun": 71,
    "Iterations per design": 0.2,
    "% Rushed design": 9,
    "Design digitization": 91,
    "SME involvement": 88,
    "Predicted Design Errors": 6
  },
  {
    "Business Unit": "Government",
    "Division": "Aftermarket",
    "Subdivision": "Friction Materials Group",
    "Department": "Vehicle Performance Dvelopment",
    "Manager": "Krishna",
    "% Design Errors": 95,
    "% Schedule delays": 90,
    "% Cost overrun": 80,
    "Iterations per design": 3,
    "% Rushed design": 17,
    "Design digitization": 57,
    "SME involvement": 39,
    "Predicted Design Errors": 11
  },
  {
    "Business Unit": "Government",
    "Division": "Electronics & ADAS",
    "Subdivision": "Advanced Driver Assistance Systems",
    "Department": "Body design functional",
    "Manager": "Aine Denari",
    "% Design Errors": 28,
    "% Schedule delays": 30,
    "% Cost overrun": 64,
    "Iterations per design": 1.8,
    "% Rushed design": 24,
    "Design digitization": 76,
    "SME involvement": 93,
    "Predicted Design Errors": 8
  },
  {
    "Business Unit": "Government",
    "Division": "Electronics & ADAS",
    "Subdivision": "Passive Safety Electronics",
    "Department": "Body designseats",
    "Manager": "Jared Jacobs",
    "% Design Errors": 11,
    "% Schedule delays": 42,
    "% Cost overrun": 37,
    "Iterations per design": 0.6,
    "% Rushed design": 47,
    "Design digitization": 41,
    "SME involvement": 47,
    "Predicted Design Errors": 2
  },
  {
    "Business Unit": "Government",
    "Division": "Passive Safety Systems",
    "Subdivision": "Inflatable Restraint Systems",
    "Department": "Quality engineering",
    "Manager": "Joe Gaus",
    "% Design Errors": 99,
    "% Schedule delays": 61,
    "% Cost overrun": 65,
    "Iterations per design": 3.3,
    "% Rushed design": 76,
    "Design digitization": 19,
    "SME involvement": 83,
    "Predicted Design Errors": 9
  },
  {
    "Business Unit": "Government",
    "Division": "Passive Safety Systems",
    "Subdivision": "Seat Belt Systems",
    "Department": "Production engineering",
    "Manager": "Dr. Petra Mayer",
    "% Design Errors": 28,
    "% Schedule delays": 69,
    "% Cost overrun": 53,
    "Iterations per design": 1.3,
    "% Rushed design": 53,
    "Design digitization": 64,
    "SME involvement": 28,
    "Predicted Design Errors": 19
  },
  {
    "Business Unit": "Government",
    "Division": "Passive Safety Systems",
    "Subdivision": "Steering Wheel Systems",
    "Department": "Vehicle Performance Dvelopment",
    "Manager": "Alexander Heilig",
    "% Design Errors": 43,
    "% Schedule delays": 96,
    "% Cost overrun": 46,
    "Iterations per design": 7.4,
    "% Rushed design": 69,
    "Design digitization": 57,
    "SME involvement": 67,
    "Predicted Design Errors": 14
  },
  {
    "Business Unit": "Government",
    "Division": "Active Safety Systems",
    "Subdivision": "Foundation Brakes",
    "Department": "Body designseats",
    "Manager": "Thomas Nejman",
    "% Design Errors": 56,
    "% Schedule delays": 5,
    "% Cost overrun": 33,
    "Iterations per design": 2.5,
    "% Rushed design": 62,
    "Design digitization": 96,
    "SME involvement": 84,
    "Predicted Design Errors": 20
  },
  {
    "Business Unit": "Government",
    "Division": "Active Safety Systems",
    "Subdivision": "Brake Controls",
    "Department": "Engineering and data innovation",
    "Manager": "Henry Whiting",
    "% Design Errors": 44,
    "% Schedule delays": 93,
    "% Cost overrun": 66,
    "Iterations per design": 8.9,
    "% Rushed design": 90,
    "Design digitization": 12,
    "SME involvement": 70,
    "Predicted Design Errors": 24
  },
  {
    "Business Unit": "Government",
    "Division": "Active Safety Systems",
    "Subdivision": "EB100",
    "Department": "Engineering design chassis",
    "Manager": "Ryan Biehl",
    "% Design Errors": 69,
    "% Schedule delays": 96,
    "% Cost overrun": 66,
    "Iterations per design": 9.4,
    "% Rushed design": 48,
    "Design digitization": 72,
    "SME involvement": 51,
    "Predicted Design Errors": 13
  },
  {
    "Business Unit": "Government",
    "Division": "Active Safety Systems",
    "Subdivision": "Steering Systems",
    "Department": "Electronic systems 1",
    "Manager": "Theo Kaster",
    "% Design Errors": 74,
    "% Schedule delays": 38,
    "% Cost overrun": 32,
    "Iterations per design": 4.8,
    "% Rushed design": 18,
    "Design digitization": 79,
    "SME involvement": 19,
    "Predicted Design Errors": 14
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Vehicle Dynamics & Control, Autonomous Driving",
    "Department": "Production engineering",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 66,
    "% Schedule delays": 5,
    "% Cost overrun": 89,
    "Iterations per design": 5.8,
    "% Rushed design": 22,
    "Design digitization": 56,
    "SME involvement": 3,
    "Predicted Design Errors": 10
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Driveline & Suspension Controls, Wheel End Solutions",
    "Department": "Vehicle Performance Dvelopment",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 59,
    "% Schedule delays": 59,
    "% Cost overrun": 65,
    "Iterations per design": 0.7,
    "% Rushed design": 90,
    "Design digitization": 31,
    "SME involvement": 33,
    "Predicted Design Errors": 8
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Vehicle Energy Management Systems",
    "Department": "Vehicle planning production engineering",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 99,
    "% Schedule delays": 15,
    "% Cost overrun": 75,
    "Iterations per design": 1.9,
    "% Rushed design": 42,
    "Design digitization": 56,
    "SME involvement": 48,
    "Predicted Design Errors": 24
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Fleet Solutions",
    "Department": "Body design 1",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 58,
    "% Schedule delays": 96,
    "% Cost overrun": 37,
    "Iterations per design": 9.4,
    "% Rushed design": 43,
    "Design digitization": 93,
    "SME involvement": 6,
    "Predicted Design Errors": 28
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Trailer Systems",
    "Department": "Body design 2",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 59,
    "% Schedule delays": 12,
    "% Cost overrun": 34,
    "Iterations per design": 6.4,
    "% Rushed design": 39,
    "Design digitization": 97,
    "SME involvement": 39,
    "Predicted Design Errors": 23
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Off-Highway Solutions",
    "Department": "Body design 3",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 15,
    "% Schedule delays": 48,
    "% Cost overrun": 49,
    "Iterations per design": 9.9,
    "% Rushed design": 59,
    "Design digitization": 100,
    "SME involvement": 53,
    "Predicted Design Errors": 2
  },
  {
    "Business Unit": "Government",
    "Division": "Commercial Vehicle Control Systems",
    "Subdivision": "Car Systems",
    "Department": "Body design functional",
    "Manager": "Fredrik Staedtler",
    "% Design Errors": 26,
    "% Schedule delays": 9,
    "% Cost overrun": 48,
    "Iterations per design": 7.9,
    "% Rushed design": 23,
    "Design digitization": 59,
    "SME involvement": 33,
    "Predicted Design Errors": 11
  }
]